FROM php:7.0-apache

RUN apt-get update && apt-get install libmcrypt-dev python python-mysql.connector -y
RUN apt-get install zlib1g-dev
RUN docker-php-ext-install mysqli pdo pdo_mysql mcrypt zip
RUN apt-get install python-requests -y


RUN a2enmod rewrite

COPY UI/ /var/www/html/

RUN sed -i.bak -e 's/localhost/db/' /var/www/html/daytona_config.ini
RUN cat /var/www/html/daytona_config.ini

RUN mkdir -p /tmp/Scheduler+Agent
COPY Scheduler+Agent/ /tmp/Scheduler+Agent/
RUN sed -i.bak -e 's/mysql-host:localhost/mysql-host:db/' /tmp/Scheduler+Agent/config.ini

RUN mkdir -p /tmp/daytona_sarmonitor
COPY Scheduler+Agent/daytona_sarmonitor/ /tmp/daytona_sarmonitor/

RUN mkdir -p /tmp/daytona_root/test_data_DH
RUN ln -s /tmp/daytona_root/test_data_DH /var/www/html/test_data
COPY TestData/ /tmp/daytona_root/test_data_DH

WORKDIR /tmp/Scheduler+Agent
CMD ./start_scheduler.sh && apache2-foreground
