FROM mysql:latest

ARG DAYTONA_USER
ARG DAYTONA_PASSWORD

RUN apt-get update && apt-get install php5-cli -y

COPY DbSchema/DbSchema.sql /docker-entrypoint-initdb.d/daytona.sql

RUN php -r "print(password_hash(getenv('DAYTONA_PASSWORD'), PASSWORD_DEFAULT));" > /tmp/passwd
RUN pass=`cat /tmp/passwd` && echo "INSERT IGNORE INTO LoginAuthentication (username, password, user_state) VALUES( '${DAYTONA_USER}', '${pass}', 'Active');" \
> /docker-entrypoint-initdb.d/users.sql
RUN rm /tmp/passwd && apt-get remove php5-cli --purge -y && apt-get autoremove -y
